---
# https://kubernetes.io/docs/concepts/services-networking/dual-stack/
- name: Stop if pod cidr is not valid
  assert:
    that: 
      - .kubernetes.networking.pod_cidr | splitList "," | len | ge 2
      - .kubernetes.networking.service_cidr | splitList "," | len | ge 2
    fail_msg: |
      kubernetes.networking.pod_cidr and kubernetes.networking.service_cidr only support ipv4_cidr/ipv6_cidr or ipv4_cidr,ipv6_cidr

- name: Stop if pod networking is not support dual-stack 
  assert:
    that: 
      - .kube_version | semverCompare ">=v1.20.0"
      - .kubernetes.networking.pod_cidr | splitList "," | first | ipFamily | eq "IPv4"
      - .kubernetes.networking.pod_cidr | splitList "," | last | ipFamily | eq "IPv6"
    fail_msg: |
      Kubernetes introduced support for pod dual-stack networking starting from version v1.20.0.
  when: .kubernetes.networking.pod_cidr | splitList "," | len | eq 2

- name: Stop if service networking is not support dual-stack 
  assert:
    that: 
      - .kube_version | semverCompare ">=v1.20.0"
      - .kubernetes.networking.service_cidr | splitList "," | first | ipFamily | eq "IPv4"
      - .kubernetes.networking.service_cidr | splitList "," | last | ipFamily | eq "IPv6"
    fail_msg: |
      Kubernetes introduced support for service dual-stack networking starting from version v1.20.0.
  when: .kubernetes.networking.service_cidr | splitList "," | len | eq 2

- name: Stop if unknown network plugin
  assert:
    that: .cluster_require.require_network_plugin | has .kubernetes.kube_network_plugin
    fail_msg: |
      kube_network_plugin:"{{ .kubernetes.kube_network_plugin }}" is not supported
  when: and .kubernetes.kube_network_plugin (ne .kubernetes.kube_network_plugin "")

# This assertion will fail on the safe side: One can indeed schedule more pods
# on a node than the CIDR-range has space for when additional pods use the host
# network namespace. It is impossible to ascertain the number of such pods at
# provisioning time, so to establish a guarantee, we factor these out.
# NOTICE: the check blatantly ignores the inet6-case
- name: Guarantee that enough network address space is available for all pods
  assert:
    that: le .kubernetes.kubelet.max_pods  (sub (pow 2 (sub 32 .kubernetes.controller_manager.kube_network_node_prefix))  2)
    fail_msg: do not schedule more pods on a node than inet addresses are available.
  when:
    - .groups.k8s_cluster | default list | has .inventory_name
    - .kubernetes.controller_manager.kube_network_node_prefix

# https://github.com/alibaba/hybridnet/wiki/Getting-Started#install
- name: Stop install hybridnet if Kubernetes version is not satisfied
  assert:
    that: .kube_version | semverCompare ">=v1.16.0"
    fail_msg: To install hybridnet in an exist Kubernetes (version > 1.16) cluster
  when:
    - .kubernetes.kube_network_plugin | eq "hyvbridnet"